name: Test Plugins

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.filter.outputs.plugins }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            plugins:
              - 'plugins/**'

  test-plugins:
    name: Test plugin - ${{ matrix.plugin }}
    needs: check-changes
    if: needs.check-changes.outputs.plugins == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        plugin:
          - remark-heading-markers
          - remark-ogp-card

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: natsukium
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: "Setup pnpm cache"
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: "Install plugin dependencies"
        run: nix develop --command bash -c "pnpm install --filter ${{ matrix.plugin }}"
      - name: "Run plugin tests"
        run: nix develop --command bash -c "pnpm -C plugins/${{ matrix.plugin }} test"
