name: Test Plugins

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.filter.outputs.plugins }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            plugins:
              - 'plugins/**'

  test-plugins:
    name: Test plugin - ${{ matrix.plugin }}
    needs: check-changes
    if: needs.check-changes.outputs.plugins == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        plugin:
          - remark-heading-markers
          - remark-ogp-card

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: natsukium
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: "Setup pnpm cache"
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: "Install plugin dependencies"
        run: nix develop --command bash -c "pnpm install --filter ${{ matrix.plugin }}"
      - name: "Run plugin tests"
        run: nix develop --command bash -c "pnpm -C plugins/${{ matrix.plugin }} test"
